@ExampleApi_HostAddress = http://localhost:5194

### List Products
GET {{ExampleApi_HostAddress}}/api/products

### Create Product
POST {{ExampleApi_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "New Product",
    "description": "A description of the new product",
    "price": 19.99,
    "stock": 100 
}